name: AST Translator

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: "Target subdomain (e.g., reference.aspose.net)"
        required: true
        default: 'reference.aspose.net'
      families:
        description: "Comma-separated list of families to process (e.g., words,cells,barcode)"
        required: true
        default: 'words,cells,barcode'
      languages:
        description: "Comma-separated list of target languages (e.g., zh,es,fr)"
        required: true
        default: 'zh'

jobs:
  prepare-matrix:
    name: Prepare Family Matrix
    runs-on: ubuntu-latest
    outputs:
      families_matrix: ${{ steps.set_matrix.outputs.families_matrix }}
    steps:
      - name: Convert families input to JSON array
        id: set_matrix
        shell: bash
        run: |
          # Split the comma-separated families and trim spaces
          IFS=',' read -ra FAM_LIST <<< "${{ inputs.families }}"
          elements=()
          for fam in "${FAM_LIST[@]}"; do
            fam="$(echo -n "$fam" | xargs)"
            if [[ -n "$fam" ]]; then
              elements+=("\"$fam\"")
            fi
          done
          json="[$(IFS=,; echo "${elements[*]}")]"
          echo "families_matrix=$json" >> $GITHUB_OUTPUT

  translate:
    name: Translate AST Files
    needs: prepare-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        family: ${{ fromJSON(needs.prepare-matrix.outputs.families_matrix) }}
    permissions:
      contents: write
    steps:
      - name: Checkout aspose.net repository
        uses: actions/checkout@v3
        with:
          repository: Aspose/aspose.net
          path: aspose-net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Checkout translationcache repository
        uses: actions/checkout@v3
        with:
          repository: smallize/translationcache
          path: translationcache
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers sentencepiece

      - name: Start auto-commit watchdog for translationcache
        run: |
          #!/bin/bash
          set -e
          # Maximum runtime: 21600 seconds (6 hours)
          MAX_RUNTIME=21600
          # Trigger auto-commit 30 minutes (1800 seconds) before timeout.
          COMMIT_BUFFER=1800
          SLEEP_DURATION=$(( MAX_RUNTIME - COMMIT_BUFFER ))
          echo "Auto-commit will trigger in $SLEEP_DURATION seconds."
          (
            sleep $SLEEP_DURATION
            echo "Auto-commit triggered; performing merge and push..."
            for lang in $(echo "${{ inputs.languages }}" | tr ',' ' '); do
              echo "Processing language $lang"
              LOCAL_FILE="aspose-net/translation/${lang}_cache.json"
              REMOTE_FILE="translationcache/${lang}_cache.json"
              if [ ! -s "$LOCAL_FILE" ]; then
                echo "Local cache file $LOCAL_FILE is empty. Skipping merge for language $lang."
                continue
              fi
              if [ ! -f "$REMOTE_FILE" ]; then
                echo "{}" > "$REMOTE_FILE"
              fi
              python aspose-net/scripts/json-merger/merger.py --input1 "$LOCAL_FILE" --input2 "$REMOTE_FILE" --output "$REMOTE_FILE"
            done
            python aspose-net/scripts/json-merger/validate_and_fix_json.py --folder "translationcache" --recursive --fix
            cd translationcache
            # Retry pull-commit-push loop up to 10 times.
            for i in {1..10}; do
              echo "Auto-commit attempt #$i"
              git pull origin "${GITHUB_REF#refs/heads/}" || true
              git add *.json
              git commit -m "Auto-commit merged translation cache for languages: ${{ inputs.languages }}" || echo "Nothing to commit"
              if git push origin "${GITHUB_REF#refs/heads/}"; then
                echo "Auto-commit push successful"
                exit 0
              else
                echo "Push failed, retrying in 5 seconds..."
                sleep 5
              fi
            done
            echo "Auto-commit push failed after multiple attempts"
            exit 1
          ) &

      - name: Run AST Translation for Family ${{ matrix.family }}
        run: |
          echo "Translating for subdomain: ${{ inputs.subdomain }}, family: ${{ matrix.family }}, languages: ${{ inputs.languages }}"
          # Construct the input path based on subdomain, family, and language folder (here assumed to be 'en')
          INPUT_PATH="aspose-net/ast/${{ inputs.subdomain }}/${{ matrix.family }}/en"
          python aspose-net/scripts/ast-translator/ast-translator.py \
            --input "$INPUT_PATH" \
            --cache_folder aspose-net/translation \
            --device auto \
            --target_languages "${{ inputs.languages }}" \
            --batch_size 8

      - name: Final Merge and Push Updated Translation Cache
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GITHUB_TOKEN: ${{ secrets.PPAT_TOKEN }}
        run: |
          #!/bin/bash
          set -e
          echo "Final merge and push process starting..."
          for lang in $(echo "${{ inputs.languages }}" | tr ',' ' '); do
            echo "Processing language $lang"
            LOCAL_FILE="aspose-net/translation/${lang}_cache.json"
            REMOTE_FILE="translationcache/${lang}_cache.json"
            if [ ! -s "$LOCAL_FILE" ]; then
              echo "Local cache file $LOCAL_FILE is empty. Skipping merge for language $lang."
              continue
            fi
            if [ ! -f "$REMOTE_FILE" ]; then
              echo "{}" > "$REMOTE_FILE"
            fi
            python aspose-net/scripts/json-merger/merger.py --input1 "$LOCAL_FILE" --input2 "$REMOTE_FILE" --output "$REMOTE_FILE"
          done
          python aspose-net/scripts/json-merger/validate_and_fix_json.py --folder "translationcache" --recursive --fix
          cd translationcache
          for i in {1..10}; do
            echo "Final commit attempt #$i"
            git pull origin "${GITHUB_REF#refs/heads/}" || true
            git add *.json
            git commit -m "Final commit merged translation cache for family: ${{ matrix.family }} and languages: ${{ inputs.languages }}" || echo "Nothing to commit"
            if git push origin "${GITHUB_REF#refs/heads/}"; then
              echo "Final push successful"
              exit 0
            else
              echo "Push failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
          echo "Final push failed after multiple attempts"
          exit 1
