name: AST2MD Converter

on:
  workflow_dispatch:

jobs:
  generate_markdown:
    name: Generate Markdown Files from AST
    runs-on: ubuntu-latest
    needs: run-dependencies
    steps:
      - name: Checkout Aspose/aspose.net Repository
        uses: actions/checkout@v3
        with:
          repository: Aspose/aspose.net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          path: aspose.net

      - name: Checkout Translation Cache Repository
        uses: actions/checkout@v3
        with:
          repository: smallize/translationcache
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          path: translationcache

      - name: Run MD Creator Script
        run: |
          cd aspose.net
          python scripts/ast-translator/ast2md-converter.py --input ast --target_languages "${{ inputs.target_language }}" --cache_folder "${GITHUB_WORKSPACE}/translationcache" 

      - name: Commit and Push Markdown Changes
        working-directory: aspose.net
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Translation Creator: Updated markdown files || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
