name: AST2MD Converter

on:
  workflow_dispatch:
    inputs:
      subdomain:
        description: "Target subdomain (e.g., reference.aspose.net or kb.aspose.net)"
        required: true
        default: "reference.aspose.net"
      families:
        description: "Comma-separated list of families (e.g., words,cells,barcode)"
        required: true
        default: "words,cells,barcode"
      target_language:
        description: "Target language code(s) for Markdown conversion (e.g., es,fr,zh)"
        required: true
        default: "de,es,fr,ja,ko,ru,zh,ar,it,pt,pl,fa,id,cs,vi,tr,th,sv,el,uk"
  workflow_call:
    inputs:
      subdomain:
        required: true
        type: string
      families:
        required: true
        type: string
      target_language:
        required: true
        type: string
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  run-dependencies:
    name: Run Dependent Workflows (AST Creator & AST Translator)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AST Creator Workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          workflow: ast-creator.yml
          ref: HEAD
          inputs: |
            subdomain: ${{ inputs.subdomain }}
            families: ${{ inputs.families }}
      - name: Trigger AST Translator Workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          workflow: ast-translator.yml
          ref: HEAD
          inputs: |
            subdomain: ${{ inputs.subdomain }}
            families: ${{ inputs.families }}
            languages: ${{ inputs.target_language }}

  generate_markdown:
    name: Generate Markdown Files from AST
    runs-on: ubuntu-latest
    needs: run-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: Aspose/aspose.net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Run MD Creator Script
        run: |
          # The script will use built‑in defaults for ast folder, output folder, cache, etc.
          python ast2md-converter.py --target_language "${{ inputs.target_language }}"

      - name: Commit and Push Markdown Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add **/*.md
          git commit -m "MD Creator: Updated markdown files for target language ${{ inputs.target_language }}" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
