name: docs.aspose.net-html
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/aspose.net
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.136.0'
          extended: true
    - name: Determine Base URL
      id: base-url
      run: |
        if [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "::set-output name=url::https://docs.aspose.net/html"
        else
          echo "::set-output name=url::https://docs-qa.aspose.net/html"
        fi
    - name: Build Aspose.html
      run: hugo --config "./configs/docs.aspose.net/html.toml" -b "${{ steps.base-url.outputs.url }}" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
    - name: Deploy Aspose.html to S3
      run: hugo deploy --config "configs/docs.aspose.net/html.toml" --maxDeletes=-1 --target "${{ github.event.inputs.environment }}" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
