name: products.aspose.net
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment for all products.aspose.net workflows'
        required: true
        default: 'staging'
        type: choice
        options:
          - production
          - staging

jobs:
  trigger_products_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get matching workflows
        run: |
          # Find workflows that match the products.aspose.net.* pattern
          workflows=$(find .github/workflows -type f -name 'products.aspose.net.*.yml')
          echo "Filtered workflows:"
          echo "$workflows"
          echo "$workflows" > workflows.txt
        shell: bash

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run matching workflows with specified environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          selected_environment="${{ github.event.inputs.environment }}"
          echo "Running all products.aspose.net workflows with environment: $selected_environment"

          while read -r workflow; do
            workflow_name=$(basename "$workflow")
            echo "Attempting to trigger $workflow_name with $selected_environment environment..."
            
            # Try to trigger each workflow with the selected environment
            if gh workflow run "$workflow_name" --field environment="$selected_environment"; then
              echo "Successfully triggered $workflow_name"
            else
              echo "Failed to trigger $workflow_name. Skipping..."
            fi
          done < workflows.txt
