# .github/workflows/query-optimizer.yml
name: Query Optimizer

on:
  # Manual trigger
  workflow_dispatch: {}

  # Weekly run: every Tuesday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 2'

jobs:
  optimize:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subdomain:
          - blog.aspose.net
          - kb.aspose.net

    steps:
      # 1. (Optional) checkout this workflows repo
      - name: Checkout workflows repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Checkout the Aspose/aspose.net repo into ./aspose-net
      - name: Checkout Aspose/aspose.net
        uses: actions/checkout@v4
        with:
          repository: Aspose/aspose.net
          token: ${{ secrets.ASPOSE_PAT }}
          path: aspose-net
          fetch-depth: 0

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4. Install script dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langchain langchain-openai openai urllib3

      # 5. Run your optimizer script for each subdomain
      - name: Run optimizer script
        working-directory: aspose-net
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/optimizer/query-optimizer.py --subdomain ${{ matrix.subdomain }}

      # 6. Commit & push any changes back to Aspose/aspose.net
      - name: Commit and push changes
        working-directory: aspose-net
        env:
          GITHUB_TOKEN: ${{ secrets.ASPOSE_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          SUB=${{ matrix.subdomain }}
          SAFE_SUB=$(echo "$SUB" | tr . -)
          DATE=$(TZ="Asia/Karachi" date +%Y%m%d)
          BRANCH="optimizer-${SAFE_SUB}-${DATE}"

          # create new branch
          git checkout -b "$BRANCH"

          # stage only the updated content for this subdomain
          git add "content/${SUB}"

          # if changes exist, commit & push
          if ! git diff --cached --quiet; then
            git commit -m "Optimize markdown content for ${SUB} (${DATE})"
            git push origin HEAD:"$BRANCH"
          else
            echo "No changes detected for ${SUB}; nothing to commit."
          fi
