name: Query Optimizer

on:
  workflow_dispatch: {}
  schedule:
    # runs every Tuesday at 00:00 UTC
    - cron: '0 0 * * 2'

jobs:
  optimize:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subdomain:
          - blog.aspose.net
          - kb.aspose.net

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langchain langchain-openai openai urllib3

      - name: Run optimizer script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/optimizer/query-optimizer.py \
            --subdomain ${{ matrix.subdomain }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          SUB=${{ matrix.subdomain }}
          SAFE_SUB=$(echo "$SUB" | tr . -)
          DATE=$(TZ="Asia/Karachi" date +%Y%m%d)
          BRANCH="optimizer-${SAFE_SUB}-${DATE}"

          git checkout -b "$BRANCH"
          git add "content/${SUB}"

          if ! git diff --cached --quiet; then
            git commit -m "Query optimized markdown content for ${SUB}:(${DATE})"
            git push origin HEAD:"$BRANCH"
          else
            echo "No changes detected for ${SUB}; nothing to commit."
          fi
