name: reference.aspose.net-generator

on:
  workflow_dispatch:
    inputs:
      products:
        description: "Comma-separated list of products (e.g., Aspose.Words,Aspose.PDF) or 'all'"
        required: true
        default: "all"
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month

jobs:
  detect-updates:
    runs-on: windows-latest
    outputs:
      to_process: ${{ steps.filter.outputs.to_process }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python -m pip install requests

      - name: Fetch Latest Versions from NuGet
        id: check_versions
        run: python scripts/check_versions.py

      - name: Filter Products for Processing
        id: filter
        shell: pwsh
        run: |
          Write-Host "DEBUG: Received products input: ${{ github.event.inputs.products }}"

          $PRODUCTS = "${{ github.event.inputs.products }}"
          if ($PRODUCTS -eq "all") {
            $PRODUCTS = (Get-Content reference/status.json | ConvertFrom-Json | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name) -join ","
          }

          Write-Host "DEBUG: Processing products: $PRODUCTS"

          # Run detect_updates.py to determine products needing updates
          $TO_PROCESS = python scripts/detect_updates.py "$PRODUCTS"

          Write-Host "DEBUG: Raw JSON from detect_updates.py:"
          Write-Host "$TO_PROCESS"

          # Ensure JSON output is correctly formatted before passing to GitHub Actions
          if ($TO_PROCESS -match "^\[.*\]$") {
            Write-Host "DEBUG: JSON is valid."
            $JSON_OUTPUT = $TO_PROCESS
          } else {
            Write-Host "DEBUG: JSON is NOT valid. Fixing..."
            $JSON_OUTPUT = "[" + $TO_PROCESS + "]"
          }

          Write-Host "DEBUG: JSON Output Before GitHub Actions Formatting:"
          Write-Host "$JSON_OUTPUT"

          # Fix: Use GITHUB_ENV correctly
          echo "to_process=$JSON_OUTPUT" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          Write-Host "DEBUG: Final value stored in GITHUB_ENV:"
          Write-Host "$JSON_OUTPUT"

  process-products:
    needs: detect-updates
    if: ${{ needs.detect-updates.outputs.to_process != '[]' && needs.detect-updates.outputs.to_process != '' }}
    runs-on: windows-latest

    steps:
      - name: Debugging Why `process-products` Is Not Running
        run: |
          echo "DEBUG: Checking received to_process value..."
          echo "DEBUG: to_process = '${{ needs.detect-updates.outputs.to_process }}'"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python -m pip install requests
