name: reference.aspose.net

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment for all reference.aspose.net workflows'
        required: true
        default: 'staging'
        type: choice
        options:
          - production
          - staging

jobs:
  trigger_reference_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get matching workflows
        run: |
          # Find workflows that match the pattern reference.aspose.net-* and exclude reference.aspose.net-generator.yml
          workflows=$(find .github/workflows -type f -name 'reference.aspose.net-*.yml' ! -name 'reference.aspose.net-generator.yml')

          # Separate the "home" workflow from the others
          home_workflow=""
          filtered_workflows=()

          while IFS= read -r workflow; do
            if [[ "$workflow" == *"reference.aspose.net-home.yml" ]]; then
              home_workflow="$workflow"
            else
              filtered_workflows+=("$workflow")
            fi
          done <<< "$workflows"

          # Save normal workflows
          printf "%s\n" "${filtered_workflows[@]}" > workflows.txt

          # Save home workflow if found
          if [[ -n "$home_workflow" ]]; then
            echo "$home_workflow" > home_workflow.txt
            echo "Home workflow found: $home_workflow"
          else
            echo "No home workflow found."
          fi

          # Debugging output
          echo "Filtered workflows (excluding home and generator):"
          cat workflows.txt
        shell: bash

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run matching workflows with specified environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          selected_environment="${{ github.event.inputs.environment }}"
          echo "Running all reference.aspose.net workflows with environment: $selected_environment"

          while IFS= read -r workflow; do
            workflow_name=$(basename "$workflow")
            echo "Attempting to trigger $workflow_name with $selected_environment environment..."
            
            # Try to trigger each workflow with the selected environment
            if gh workflow run "$workflow_name" --field environment="$selected_environment"; then
              echo "Successfully triggered $workflow_name"
            else
              echo "Failed to trigger $workflow_name. Skipping..."
            fi
          done < workflows.txt

      - name: Delay before triggering home workflow
        run: |
          echo "Waiting for 30 seconds before triggering the home workflow..."
          sleep 30
        if: hashFiles('home_workflow.txt') != ''

      - name: Run the home workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          home_workflow=$(cat home_workflow.txt)
          workflow_name=$(basename "$home_workflow")
          selected_environment="${{ github.event.inputs.environment }}"
          echo "Triggering home workflow: $workflow_name with environment: $selected_environment"

          if gh workflow run "$workflow_name" --field environment="$selected_environment"; then
            echo "Successfully triggered $workflow_name"
          else
            echo "Failed to trigger $workflow_name."
          fi
        if: hashFiles('home_workflow.txt') != ''
