name: reference.aspose.net-generator

on:
  workflow_dispatch:
    inputs:
      products:
        description: "Comma-separated list of products (e.g., Aspose.Words,Aspose.PDF) or 'all'"
        required: true
        default: "all"
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month

jobs:
  detect-updates:
    runs-on: windows-latest
    outputs:
      to_process: ${{ steps.filter.outputs.to_process }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python -m pip install requests

      - name: Fetch Latest Versions from NuGet
        id: check_versions
        run: python scripts/check_versions.py

      - name: Filter Products for Processing
        id: filter
        shell: pwsh
        run: |
          $PRODUCTS = "${{ github.event.inputs.products }}"
          if ($PRODUCTS -eq "all") {
            $PRODUCTS = (Get-Content reference/status.json | ConvertFrom-Json | Get-Member -MemberType NoteProperty | Select-Object -ExpandProperty Name) -join ","
          }

          # Run detect_updates.py to determine products needing updates
          $TO_PROCESS = python scripts/detect_updates.py "$PRODUCTS"

          # Ensure JSON output is correctly formatted before passing to GitHub Actions
          if ($TO_PROCESS -match "^\[.*\]$") {
            Write-Host "DEBUG: JSON is valid."
            $JSON_OUTPUT = $TO_PROCESS
          } else {
            Write-Host "DEBUG: JSON is NOT valid. Attempting to fix..."
            $JSON_OUTPUT = "[" + $TO_PROCESS + "]"
          }

          Write-Host "DEBUG: JSON Output Before GitHub Actions Formatting:"
          Write-Host $JSON_OUTPUT

          # Print `to_process` for debugging in GitHub Actions
          echo "DEBUG: GitHub Actions should receive `to_process` as:"
          echo $JSON_OUTPUT

          # **Fix: Use GitHub Actions Output Correctly**
          echo "::set-output name=to_process::$JSON_OUTPUT"

  process-products:
    needs: detect-updates
    if: ${{ needs.detect-updates.outputs.to_process != '[]' && needs.detect-updates.outputs.to_process != '' }}
    runs-on: windows-latest
    strategy:
      matrix:
        product: ${{ fromJson(needs.detect-updates.outputs.to_process) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python -m pip install requests
