name: Sitemap Indexer

on:
  workflow_dispatch: # Allows manual execution

jobs:
  submit_sitemaps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 requests

      - name: Prepare batches
        run: python script/sitemap_parser.py 

      - name: Submit batches to Google
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python script/batch_submitter.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add logs/processed_urls.json logs/batches_to_submit.json
          git commit -m "Update processed URLs log" || echo "No changes to commit"
          git push
